### ISSUE TITLE
Want to talk

### ISSUE THREAD

**Issue by pranayteaches** [chinglamchoi/Corona-Net#1]
hey i have a question
Did you delete Aicodein?

If you wish can I talk to you?
If yes than share your social media handle an than I will delete the issue
Else no issue be happy :)

**Comment by chinglamchoi** [comment]
hey lol, why don't we chat on Linkedin? https://www.linkedin.com/in/ching-lam-choi-7609541a0/

**Comment by pranayteaches** [comment]
I dont have linkedin premium. can we chat on telegram
Here is my id
@pranayteaches

**Comment by chinglamchoi** [comment]
Hi, I don't have linkedin premium either (nor telegram), if you don't mind connecting, I think we can chat there?

**Comment by pranayteaches** [comment]
but this is public. if you don't mind you may download telegram we all google codein winners chat there
